extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - prettier
rules:
  "prettier/prettier": "error"
  "react/react-in-jsx-scope": "off"
  "react/jsx-uses-react": "off"
  no-shadow: off
  "@typescript-eslint/no-shadow":
    - error
  no-use-before-define: off
  "@typescript-eslint/no-use-before-define":
    - error
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .tsx
  complexity:
    - error
    - 10
  no-await-in-loop: warn
  no-eval: error
  no-implied-eval: error
  prefer-promise-reject-errors: warn
env:
  browser: true
  jest/globals: true
settings:
  react:
    pragma: React
